### ISSUE TITLE
Opening the i2p address book causes every link displayed to auto open

### ISSUE THREAD

**Issue by Ryemantis** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#103] opened 2020-12-11 23:23 UTC
When navigating to the I2p addressbook (http://127.0.0.1:7657/dns), if I click on any of the private, local, or router records the extension will immediately open every link displayed on the page in a new tab.

**Comment by eyedeekay** [comment] 2020-12-21 22:22
This has the same root cause as the other issue you opened, it would appear that since the img tags contain urls which contain queries that *look* like I2P URL's being misdirected to search engines, the plugin attempts to isolate them. Also will be fixed shortly.

**Comment by eyedeekay** [comment] 2020-12-21 23:24
Fixed. AMO usually pushes out within an hour or so, see 0.96

**Closed** 2020-12-21 23:25 UTC
